version: 2
registries:
  artifactory-docker:
    type: docker-registry
    url: https://ezcater-production.jfrog.io
    username: "${{secrets.ARTIFACTORY_USERNAME}}"
    password: "${{secrets.ARTIFACTORY_PASSWORD}}"
  artifactory-rubygems:
    type: rubygems-server
    url: https://ezcater.jfrog.io/ezcater/api/gems/ezcater-gem-source
    username: "${{secrets.ARTIFACTORY_USERNAME}}"
    password: "${{secrets.ARTIFACTORY_PASSWORD}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: rspec-rails
    versions:
    - 4.1.1
  - dependency-name: grape
    versions:
    - 1.5.1
    - 1.5.2
  - dependency-name: salsify_rubocop
    versions:
    - 1.0.1
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: sentry-raven
    versions:
    - 3.1.1
  registries:
  - artifactory-rubygems
- package-ecosystem: docker
  directory: "/"
  registries:
    - artifactory-docker
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
