dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.6.3
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database "avro-schema-registry_test";' -U postgres
script:
  - bundle exec rubocop
  - bundle exec rspec
