language: ruby
rvm:
  - 2.3.3
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database "avro-schema-registry_test";' -U postgres
script:
  - bundle exec rubocop
  - bundle exec rspec
