version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.2.2
      - image: cimg/postgres:14.7
        environment:
          POSTGRES_USER: "ubuntu"
          POSTGRES_DB: "avro-schema-registry_test"
          POSTGRES_HOST_AUTH_METHOD: "trust"
    environment:
      RACK_ENV: "test"
      RAILS_ENV: "test"
      CIRCLE_TEST_REPORTS: "test-results"
      DB_HOST: "localhost"
      DB_USER: "ubuntu"
    working_directory: ~/avro-schema-registry
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gems-ruby-3.2.2-{{ checksum "Gemfile.lock" }}
            - v1-gems-ruby-3.2.2-
      - run:
          name: Install Gems
          command: |
            if ! bundle check --path=vendor/bundle; then
              bundle install --path=vendor/bundle --jobs=4 --retry=3
              bundle clean
            fi
      - save_cache:
          key: v1-gems-ruby-3.2.2-{{ checksum "Gemfile.lock" }}
          paths:
            - "vendor/bundle"
      - run:
          name: Run Rubocop
          command: bundle exec rubocop --config .rubocop.yml
      - run:
          name: Run Tests
          command: |
            bundle exec rspec --format RspecJunitFormatter --out $CIRCLE_TEST_REPORTS/rspec/junit.xml --format progress spec
      - store_test_results:
          path: "test-results"
      - store_artifacts:
          path: "log"
workflows:
  build:
    jobs:
      - build
