#!/bin/bash
network_name="ezcater-development-network"

network_options=$(docker network inspect --format "{{.Options}}" $network_name 2>/dev/null)

if [[ ! $? -eq 0 ]]; then

  echo "Creating development network ..."
  docker network create $network_name > /dev/null || exit 1

elif [[ "$network_options" =~ host_binding_ipv4 ]]; then
  echo "The $network_name must be removed and recreated."
  echo "All running containers on the network will be stopped."
  read -p "Do you want to proceed? [y/N] " -n 1 -r
  echo

  if [[ $REPLY =~ ^[Yy]$ ]]; then
    set -e

    containers="$(docker network inspect --format "{{range .Containers}}{{.Name}} {{end }}" $network_name)"
    if [[ ! -z "$containers" ]]; then
      echo "Stopping containers ..."
      docker stop $containers
    fi

    echo "Recreating network ..."
    docker network rm $network_name > /dev/null
    docker network create $network_name > /dev/null
    set +e
  else
    echo "Exiting" && exit 1
  fi
fi
