#!/bin/bash
. "$(dirname "$0")"/artifactory_setup
. "$(dirname "$0")"/check_network
if docker-compose exec -T schema-registry-web echo "Running in existing schema-registry-web container ..." 2>/dev/null
then
  run_or_exec="exec"
else
  run_or_exec="run --rm"
fi

docker-compose $run_or_exec schema-registry-web bash -c "$*"
